USE [FORENSIC]
GO
/****** Object:  User [dbms]    Script Date: 14-02-2023 14:18:47 ******/
CREATE USER [dbms] FOR LOGIN [dbms] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [dbms]
GO
/****** Object:  Table [dbo].[ADMIN]    Script Date: 14-02-2023 14:18:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN](
	[AdminID] [varchar](20) NOT NULL,
	[AdminName] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[AdminID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CRIMES]    Script Date: 14-02-2023 14:18:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CRIMES](
	[CaseID] [varchar](20) NOT NULL,
	[Place_of_occurance] [varchar](20) NULL,
	[DetectiveID] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[CaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DETECTIVE]    Script Date: 14-02-2023 14:18:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DETECTIVE](
	[DetectiveID] [varchar](20) NOT NULL,
	[DetectiveName] [varchar](20) NULL,
	[Gender] [varchar](20) NULL,
	[Age] [int] NULL,
	[AdminID] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[DetectiveID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EVIDENCE_FOUND]    Script Date: 14-02-2023 14:18:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVIDENCE_FOUND](
	[CaseID] [varchar](20) NOT NULL,
	[Evidence] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CaseID] ASC,
	[Evidence] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FINGERPRINT]    Script Date: 14-02-2023 14:18:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FINGERPRINT](
	[CaseID] [varchar](20) NOT NULL,
	[Fingerprint] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CaseID] ASC,
	[Fingerprint] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUSPECTS]    Script Date: 14-02-2023 14:18:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUSPECTS](
	[CaseID] [varchar](20) NOT NULL,
	[Suspects] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CaseID] ASC,
	[Suspects] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CRIMES]  WITH CHECK ADD FOREIGN KEY([DetectiveID])
REFERENCES [dbo].[DETECTIVE] ([DetectiveID])
GO
ALTER TABLE [dbo].[DETECTIVE]  WITH CHECK ADD FOREIGN KEY([AdminID])
REFERENCES [dbo].[ADMIN] ([AdminID])
GO
ALTER TABLE [dbo].[EVIDENCE_FOUND]  WITH CHECK ADD FOREIGN KEY([CaseID])
REFERENCES [dbo].[CRIMES] ([CaseID])
GO
ALTER TABLE [dbo].[FINGERPRINT]  WITH CHECK ADD FOREIGN KEY([CaseID])
REFERENCES [dbo].[CRIMES] ([CaseID])
GO
ALTER TABLE [dbo].[SUSPECTS]  WITH CHECK ADD FOREIGN KEY([CaseID])
REFERENCES [dbo].[CRIMES] ([CaseID])
GO
